### ISSUE TITLE
classnames zoals stylguide of specifieker 

### ISSUE THREAD

**Issue by Nayomekaia** [poormoa00/look-and-feel-corporate-identity#14]
hiii,

in de styleguide staan er heel veel classnames voor de verschillende radio bvb 
<img width="648" alt="image" src="https://github.com/user-attachments/assets/35e49ccf-3557-4612-acf1-6a6b745d747d">
 
hierin zie je in de classname dat het over 100%nl gaat en de kleuren daarvan, dit soort classnames zie ik niet terug in je eigen code, de classnames zijn best wel algemeen zoals event-card ( maar welke event-card is dit dan ).

in het kort, gebruik clasnames netzoals het in de styleguide staat of specifieker zodat het later makkelijker te linken is  in je css  en ook duidelijker voor bvb je teamgenoten die naar je code kijken over wat het gaat.

**Comment by poormoa00** [comment]
https://poormoa00.github.io/look-and-feel-corporate-identity/
