### ISSUE TITLE
images

### ISSUE THREAD

**Issue by Luc-Hoogerwerf** [poormoa00/look-and-feel-corporate-identity#15]
Vergeet niet je plaatjes over te zetten naar je nieuwe repo. Op het moment is er alleen een alt tekst te zien

In style.css en mediahuis.css staan veel stukken code die identiek aan elkaar zijn. Probeer te kijken welke code in style.css echt nodig is en welke je weg kan halen (omdat ze al in mediahuis.css staan)

er worden classes gebruikt als 'header-nav-primary', deze zijn niet te vinden in de css bestanden. Probeer deze wel toe te voegen zodat ook de styling wordt toegepast op de navigatie.

**Comment by poormoa00** [comment]
Zal ik zeker doen, bedankt voor je feedback!
