### ISSUE TITLE
feedback opdrachtgever: tijdlijn wat dichterbij de event-cards halen.

### ISSUE THREAD

**Issue by poormoa00** [poormoa00/look-and-feel-corporate-identity#18]

**Comment by Mikiyas-hs** [comment]
https://github.com/poormoa00/look-and-feel-corporate-identity/blob/ae4fca9890619de5e98b2507245705c2a2aadc69/style.css#L98-L103 

waarschijnlijk blijft jou tijdlijn niet op 1 plek staan omdat je geen 'position: absolute' in je main hebt gezet als je dit toepast laat het me weten of het je is gelukt

**Comment by poormoa00** [comment]
971fe46c5b89e86b0d00e1e9d6c028d88203e790
